repo_name: zkan/brag-docs
repo_url: https://github.com/zkan/brag-docs
site_name: Kan Ouivirach - Brag Docs
site_url: https://zkan.github.io/brag-docs

theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: false
  - search

nav:
  - Home: index.md
  - 2025: 2025.md
  - 2024: 2024.md
  - 2023: 2023.md
  - 2022: 2022.md
  - 2021: 2021.md
  - 2020: 2020.md
  - 2019: 2019.md
  - 2017: 2017.md
